/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiDocsRouteImport } from './routes/api/docs'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardKeysRouteImport } from './routes/dashboard/keys'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as VerifyErrorRouteImport } from './routes/verify.error'
import { Route as VerifySuccessRouteImport } from './routes/verify.success'
import { Route as ApiPublicKeysRouteImport } from './routes/api/public/keys'
import { Route as ApiPublicTokensRouteImport } from './routes/api/public/tokens'
import { Route as ApiAuthDiscordCallbackRouteImport } from './routes/api/auth/discord/callback'
import { Route as ApiAuthDiscordLogoutRouteImport } from './routes/api/auth/discord/logout'
import { Route as ApiAuthDiscordStartRouteImport } from './routes/api/auth/discord/start'
import { Route as ApiAuthRobloxCallbackRouteImport } from './routes/api/auth/roblox/callback'
import { Route as ApiAuthRobloxStartRouteImport } from './routes/api/auth/roblox/start'
import { Route as ApiPublicKeysAuthorizeRouteImport } from './routes/api/public/keys.authorize'
import { Route as ApiPublicTokenTokenRouteImport } from './routes/api/public/token.$token'
import { Route as ApiPublicVerificationDiscordIdRouteImport } from './routes/api/public/verification.$discordId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api/docs',
  path: '/api/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifyErrorRoute = VerifyErrorRouteImport.update({
  id: '/verify/error',
  path: '/verify/error',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySuccessRoute = VerifySuccessRouteImport.update({
  id: '/verify/success',
  path: '/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeysRoute = ApiPublicKeysRouteImport.update({
  id: '/api/public/keys',
  path: '/api/public/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTokensRoute = ApiPublicTokensRouteImport.update({
  id: '/api/public/tokens',
  path: '/api/public/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordCallbackRoute = ApiAuthDiscordCallbackRouteImport.update({
  id: '/api/auth/discord/callback',
  path: '/api/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordLogoutRoute = ApiAuthDiscordLogoutRouteImport.update({
  id: '/api/auth/discord/logout',
  path: '/api/auth/discord/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDiscordStartRoute = ApiAuthDiscordStartRouteImport.update({
  id: '/api/auth/discord/start',
  path: '/api/auth/discord/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRobloxCallbackRoute = ApiAuthRobloxCallbackRouteImport.update({
  id: '/api/auth/roblox/callback',
  path: '/api/auth/roblox/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRobloxStartRoute = ApiAuthRobloxStartRouteImport.update({
  id: '/api/auth/roblox/start',
  path: '/api/auth/roblox/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeysAuthorizeRoute = ApiPublicKeysAuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => ApiPublicKeysRoute,
} as any)
const ApiPublicTokenTokenRoute = ApiPublicTokenTokenRouteImport.update({
  id: '/api/public/token/$token',
  path: '/api/public/token/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerificationDiscordIdRoute =
  ApiPublicVerificationDiscordIdRouteImport.update({
    id: '/api/public/verification/$discordId',
    path: '/api/public/verification/$discordId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/docs': typeof ApiDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/keys': typeof ApiPublicKeysRouteWithChildren
  '/api/public/tokens': typeof ApiPublicTokensRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/logout': typeof ApiAuthDiscordLogoutRoute
  '/api/auth/discord/start': typeof ApiAuthDiscordStartRoute
  '/api/auth/roblox/callback': typeof ApiAuthRobloxCallbackRoute
  '/api/auth/roblox/start': typeof ApiAuthRobloxStartRoute
  '/api/public/keys/authorize': typeof ApiPublicKeysAuthorizeRoute
  '/api/public/token/$token': typeof ApiPublicTokenTokenRoute
  '/api/public/verification/$discordId': typeof ApiPublicVerificationDiscordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/docs': typeof ApiDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/keys': typeof ApiPublicKeysRouteWithChildren
  '/api/public/tokens': typeof ApiPublicTokensRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/logout': typeof ApiAuthDiscordLogoutRoute
  '/api/auth/discord/start': typeof ApiAuthDiscordStartRoute
  '/api/auth/roblox/callback': typeof ApiAuthRobloxCallbackRoute
  '/api/auth/roblox/start': typeof ApiAuthRobloxStartRoute
  '/api/public/keys/authorize': typeof ApiPublicKeysAuthorizeRoute
  '/api/public/token/$token': typeof ApiPublicTokenTokenRoute
  '/api/public/verification/$discordId': typeof ApiPublicVerificationDiscordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/docs': typeof ApiDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/keys': typeof ApiPublicKeysRouteWithChildren
  '/api/public/tokens': typeof ApiPublicTokensRoute
  '/api/auth/discord/callback': typeof ApiAuthDiscordCallbackRoute
  '/api/auth/discord/logout': typeof ApiAuthDiscordLogoutRoute
  '/api/auth/discord/start': typeof ApiAuthDiscordStartRoute
  '/api/auth/roblox/callback': typeof ApiAuthRobloxCallbackRoute
  '/api/auth/roblox/start': typeof ApiAuthRobloxStartRoute
  '/api/public/keys/authorize': typeof ApiPublicKeysAuthorizeRoute
  '/api/public/token/$token': typeof ApiPublicTokenTokenRoute
  '/api/public/verification/$discordId': typeof ApiPublicVerificationDiscordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/docs'
    | '/dashboard/keys'
    | '/dashboard/overview'
    | '/verify/error'
    | '/verify/success'
    | '/dashboard/'
    | '/api/public/keys'
    | '/api/public/tokens'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/logout'
    | '/api/auth/discord/start'
    | '/api/auth/roblox/callback'
    | '/api/auth/roblox/start'
    | '/api/public/keys/authorize'
    | '/api/public/token/$token'
    | '/api/public/verification/$discordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/docs'
    | '/dashboard/keys'
    | '/dashboard/overview'
    | '/verify/error'
    | '/verify/success'
    | '/dashboard'
    | '/api/public/keys'
    | '/api/public/tokens'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/logout'
    | '/api/auth/discord/start'
    | '/api/auth/roblox/callback'
    | '/api/auth/roblox/start'
    | '/api/public/keys/authorize'
    | '/api/public/token/$token'
    | '/api/public/verification/$discordId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/docs'
    | '/dashboard/keys'
    | '/dashboard/overview'
    | '/verify/error'
    | '/verify/success'
    | '/dashboard/'
    | '/api/public/keys'
    | '/api/public/tokens'
    | '/api/auth/discord/callback'
    | '/api/auth/discord/logout'
    | '/api/auth/discord/start'
    | '/api/auth/roblox/callback'
    | '/api/auth/roblox/start'
    | '/api/public/keys/authorize'
    | '/api/public/token/$token'
    | '/api/public/verification/$discordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiDocsRoute: typeof ApiDocsRoute
  VerifyErrorRoute: typeof VerifyErrorRoute
  VerifySuccessRoute: typeof VerifySuccessRoute
  ApiPublicKeysRoute: typeof ApiPublicKeysRouteWithChildren
  ApiPublicTokensRoute: typeof ApiPublicTokensRoute
  ApiAuthDiscordCallbackRoute: typeof ApiAuthDiscordCallbackRoute
  ApiAuthDiscordLogoutRoute: typeof ApiAuthDiscordLogoutRoute
  ApiAuthDiscordStartRoute: typeof ApiAuthDiscordStartRoute
  ApiAuthRobloxCallbackRoute: typeof ApiAuthRobloxCallbackRoute
  ApiAuthRobloxStartRoute: typeof ApiAuthRobloxStartRoute
  ApiPublicTokenTokenRoute: typeof ApiPublicTokenTokenRoute
  ApiPublicVerificationDiscordIdRoute: typeof ApiPublicVerificationDiscordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/api/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify/error': {
      id: '/verify/error'
      path: '/verify/error'
      fullPath: '/verify/error'
      preLoaderRoute: typeof VerifyErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/success': {
      id: '/verify/success'
      path: '/verify/success'
      fullPath: '/verify/success'
      preLoaderRoute: typeof VerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keys': {
      id: '/api/public/keys'
      path: '/api/public/keys'
      fullPath: '/api/public/keys'
      preLoaderRoute: typeof ApiPublicKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tokens': {
      id: '/api/public/tokens'
      path: '/api/public/tokens'
      fullPath: '/api/public/tokens'
      preLoaderRoute: typeof ApiPublicTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/callback': {
      id: '/api/auth/discord/callback'
      path: '/api/auth/discord/callback'
      fullPath: '/api/auth/discord/callback'
      preLoaderRoute: typeof ApiAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/logout': {
      id: '/api/auth/discord/logout'
      path: '/api/auth/discord/logout'
      fullPath: '/api/auth/discord/logout'
      preLoaderRoute: typeof ApiAuthDiscordLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/discord/start': {
      id: '/api/auth/discord/start'
      path: '/api/auth/discord/start'
      fullPath: '/api/auth/discord/start'
      preLoaderRoute: typeof ApiAuthDiscordStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/roblox/callback': {
      id: '/api/auth/roblox/callback'
      path: '/api/auth/roblox/callback'
      fullPath: '/api/auth/roblox/callback'
      preLoaderRoute: typeof ApiAuthRobloxCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/roblox/start': {
      id: '/api/auth/roblox/start'
      path: '/api/auth/roblox/start'
      fullPath: '/api/auth/roblox/start'
      preLoaderRoute: typeof ApiAuthRobloxStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keys/authorize': {
      id: '/api/public/keys/authorize'
      path: '/authorize'
      fullPath: '/api/public/keys/authorize'
      preLoaderRoute: typeof ApiPublicKeysAuthorizeRouteImport
      parentRoute: typeof ApiPublicKeysRoute
    }
    '/api/public/token/$token': {
      id: '/api/public/token/$token'
      path: '/api/public/token/$token'
      fullPath: '/api/public/token/$token'
      preLoaderRoute: typeof ApiPublicTokenTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verification/$discordId': {
      id: '/api/public/verification/$discordId'
      path: '/api/public/verification/$discordId'
      fullPath: '/api/public/verification/$discordId'
      preLoaderRoute: typeof ApiPublicVerificationDiscordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiPublicKeysRouteChildren {
  ApiPublicKeysAuthorizeRoute: typeof ApiPublicKeysAuthorizeRoute
}

const ApiPublicKeysRouteChildren: ApiPublicKeysRouteChildren = {
  ApiPublicKeysAuthorizeRoute: ApiPublicKeysAuthorizeRoute,
}

const ApiPublicKeysRouteWithChildren = ApiPublicKeysRoute._addFileChildren(
  ApiPublicKeysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiDocsRoute: ApiDocsRoute,
  VerifyErrorRoute: VerifyErrorRoute,
  VerifySuccessRoute: VerifySuccessRoute,
  ApiPublicKeysRoute: ApiPublicKeysRouteWithChildren,
  ApiPublicTokensRoute: ApiPublicTokensRoute,
  ApiAuthDiscordCallbackRoute: ApiAuthDiscordCallbackRoute,
  ApiAuthDiscordLogoutRoute: ApiAuthDiscordLogoutRoute,
  ApiAuthDiscordStartRoute: ApiAuthDiscordStartRoute,
  ApiAuthRobloxCallbackRoute: ApiAuthRobloxCallbackRoute,
  ApiAuthRobloxStartRoute: ApiAuthRobloxStartRoute,
  ApiPublicTokenTokenRoute: ApiPublicTokenTokenRoute,
  ApiPublicVerificationDiscordIdRoute: ApiPublicVerificationDiscordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
