/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifySuccessRouteImport } from './routes/verify.success'
import { Route as VerifyErrorRouteImport } from './routes/verify.error'
import { Route as ApiPublicVerificationDiscordIdRouteImport } from './routes/api/public/verification.$discordId'
import { Route as ApiAuthRobloxStartRouteImport } from './routes/api/auth/roblox/start'
import { Route as ApiAuthRobloxCallbackRouteImport } from './routes/api/auth/roblox/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySuccessRoute = VerifySuccessRouteImport.update({
  id: '/verify/success',
  path: '/verify/success',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyErrorRoute = VerifyErrorRouteImport.update({
  id: '/verify/error',
  path: '/verify/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerificationDiscordIdRoute =
  ApiPublicVerificationDiscordIdRouteImport.update({
    id: '/api/public/verification/$discordId',
    path: '/api/public/verification/$discordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRobloxStartRoute = ApiAuthRobloxStartRouteImport.update({
  id: '/api/auth/roblox/start',
  path: '/api/auth/roblox/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRobloxCallbackRoute = ApiAuthRobloxCallbackRouteImport.update({
  id: '/api/auth/roblox/callback',
  path: '/api/auth/roblox/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/api/auth/roblox/callback': typeof ApiAuthRobloxCallbackRoute
  '/api/auth/roblox/start': typeof ApiAuthRobloxStartRoute
  '/api/public/verification/$discordId': typeof ApiPublicVerificationDiscordIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/api/auth/roblox/callback': typeof ApiAuthRobloxCallbackRoute
  '/api/auth/roblox/start': typeof ApiAuthRobloxStartRoute
  '/api/public/verification/$discordId': typeof ApiPublicVerificationDiscordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verify/error': typeof VerifyErrorRoute
  '/verify/success': typeof VerifySuccessRoute
  '/api/auth/roblox/callback': typeof ApiAuthRobloxCallbackRoute
  '/api/auth/roblox/start': typeof ApiAuthRobloxStartRoute
  '/api/public/verification/$discordId': typeof ApiPublicVerificationDiscordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify/error'
    | '/verify/success'
    | '/api/auth/roblox/callback'
    | '/api/auth/roblox/start'
    | '/api/public/verification/$discordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify/error'
    | '/verify/success'
    | '/api/auth/roblox/callback'
    | '/api/auth/roblox/start'
    | '/api/public/verification/$discordId'
  id:
    | '__root__'
    | '/'
    | '/verify/error'
    | '/verify/success'
    | '/api/auth/roblox/callback'
    | '/api/auth/roblox/start'
    | '/api/public/verification/$discordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerifyErrorRoute: typeof VerifyErrorRoute
  VerifySuccessRoute: typeof VerifySuccessRoute
  ApiAuthRobloxCallbackRoute: typeof ApiAuthRobloxCallbackRoute
  ApiAuthRobloxStartRoute: typeof ApiAuthRobloxStartRoute
  ApiPublicVerificationDiscordIdRoute: typeof ApiPublicVerificationDiscordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/success': {
      id: '/verify/success'
      path: '/verify/success'
      fullPath: '/verify/success'
      preLoaderRoute: typeof VerifySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/error': {
      id: '/verify/error'
      path: '/verify/error'
      fullPath: '/verify/error'
      preLoaderRoute: typeof VerifyErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verification/$discordId': {
      id: '/api/public/verification/$discordId'
      path: '/api/public/verification/$discordId'
      fullPath: '/api/public/verification/$discordId'
      preLoaderRoute: typeof ApiPublicVerificationDiscordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/roblox/start': {
      id: '/api/auth/roblox/start'
      path: '/api/auth/roblox/start'
      fullPath: '/api/auth/roblox/start'
      preLoaderRoute: typeof ApiAuthRobloxStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/roblox/callback': {
      id: '/api/auth/roblox/callback'
      path: '/api/auth/roblox/callback'
      fullPath: '/api/auth/roblox/callback'
      preLoaderRoute: typeof ApiAuthRobloxCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerifyErrorRoute: VerifyErrorRoute,
  VerifySuccessRoute: VerifySuccessRoute,
  ApiAuthRobloxCallbackRoute: ApiAuthRobloxCallbackRoute,
  ApiAuthRobloxStartRoute: ApiAuthRobloxStartRoute,
  ApiPublicVerificationDiscordIdRoute: ApiPublicVerificationDiscordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
